AWSTemplateFormatVersion: '2010-09-09'
Resources:

  MyStaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: the-alchemist
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: the-alchemist
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: arn:aws:s3:::the-alchemist/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::654654455942:distribution/${CloudFrontDistribution}"

  MyACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: www.the-alchemist.link
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - www.the-alchemist.link

  # CloudFrontOriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: this is a AWS::CloudFront::CloudFrontOriginAccessIdentity for the-alchemist


  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "origin access control(OAC) for allowing cloudfront to access S3 bucket"
        Name: the-alchemist
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4


  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - MyStaticWebsiteBucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: the-alchemist.s3.ap-southeast-2.amazonaws.com
            Id: the-alchemist
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: "true"
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        HttpVersion: http3
        Aliases:
          - www.the-alchemist.link
        ViewerCertificate:
          AcmCertificateArn: !Ref MyACMCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: true
          TargetOriginId: the-alchemist
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https

  Route53AliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: www.the-alchemist.link
      Type: A
      AliasTarget:
        HostedZoneId: Z06958611JDYVCG41K93R
        DNSName: !GetAtt CloudFrontDistribution.DomainName
