AWSTemplateFormatVersion: '2010-09-09'
Resources:

  MyStaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: the-alchemist-link
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: the-alchemist-link
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: arn:aws:s3:::the-alchemist-link/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::654654455942:distribution/${CloudFrontDistribution}"



  # CloudFrontOriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: this is a AWS::CloudFront::CloudFrontOriginAccessIdentity for the-alchemist

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "origin access control(OAC) for allowing cloudfront to access S3 bucket"
        Name: the-alchemist
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4


  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - MyStaticWebsiteBucket
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: the-alchemist-link.s3.ap-southeast-2.amazonaws.com
            Id: the-alchemist
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: "true"
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /error.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        HttpVersion: http3
        Aliases:
          - www.the-alchemist.link
        ViewerCertificate:
          # To use a certificate in AWS Certificate Manager (ACM) to require HTTPS between viewers and CloudFront, make sure you request (or import) the certificate in the US East (N. Virginia) Region (us-east-1).
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html
          AcmCertificateArn: arn:aws:acm:us-east-1:654654455942:certificate/a98c772e-237d-4004-81b7-71bd8c1af3f9
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: true
          TargetOriginId: the-alchemist
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https

  Route53AliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: www.the-alchemist.link
      Type: A
      HostedZoneId: Z06958611JDYVCG41K93R
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        # For CloudFront distributions, the value is always Z2FDTNDATAQYW2
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-aliastarget.html#cfn-route53-recordset-aliastarget-hostedzoneid
