name: DeployBudgetAlertTriggeredLambda

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-lambda.yaml'
      - 'cloudformation/lambda-for-budget-alert.yaml'
      - 'lambda/**'

jobs:
  deploy_lambda:
    name: DeployLambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEEMO1DAI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEEMO1DAI }}
          aws-region: ap-southeast-2
      
      - name: Upload lambda to S3 bucket
        run: |
          zip -rj budget_alert_action.zip lambda
          aws s3 cp budget_alert_action.zip s3://the-alchemist-cloudformation/lambda/

      - name: DeployCFNStack
        id: cfn-lambda
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: budget-alert-triggered-lambda
          template: cloudformation/lambda-for-budget-alert.yaml
          capabilities: CAPABILITY_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND
          no-fail-on-empty-changeset: "1"
