name: DeployPrerequisites
# this has to be deployed before other deployments

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-prerequisites.yaml'
      - 'cloudformation/prerequisite-us-east-1.yaml'
      - 'cloudformation/prerequisite-ap-southeast-2.yaml'

jobs:
  deploy_basic:
    name: DeployPrerequisite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: setcreds1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEEMO1DAI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEEMO1DAI }}
          aws-region: us-east-1
      
      - name: DeployCFNStack_us-east-1
        id: cfn-prerequisite-1
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: the-alchemist-acm
          template: cloudformation/prerequisite-us-east-1.yaml
          no-fail-on-empty-changeset: "1"

      - name: Configure AWS credentials
        id: setcreds2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEEMO1DAI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEEMO1DAI }}
          aws-region: ap-southeast-2
      
      - name: DeployCFNStack_ap-southeast-2
        id: cfn-prerequisite-2
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: prerequisite-ap-southeast-2
          template: cloudformation/prerequisite-ap-southeast-2.yaml
          no-fail-on-empty-changeset: "1"
