name: DeployStaticPage

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-static-page.yaml'
      - 'cloudformation/static-page-stack.yaml'
      - 'eleventy/**'

jobs:
  static_page:
    name: DeployStaticPage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEEMO1DAI }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEEMO1DAI }}
          aws-region: ap-southeast-2
      
      - name: DeployCFNStack
        id: cfn-static-page
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: the-alchemist
          template: cloudformation/static-page-stack.yaml
          no-fail-on-empty-changeset: "1"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Cache Eleventy .cache
        uses: actions/cache@v3
        with:
          path: eleventy/.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - run: |
          cd eleventy
          npm install
          npm run build

      - name: Upload files to S3 bucket
        run: aws s3 sync eleventy/_site s3://www.the-alchemist.link/
